### ISSUE TITLE
erreur listener ?

### ISSUE THREAD

**Issue by RAUPETIT** [thelia-modules/FlatFeeDelivery#8]
J'ai remarqué dans EventManager.php la ligne :

if($event->getOrder()->getDeliveryModuleId() === FlatFeeDelivery::getModuleCode())

Ne faudrait-il pas remplacer par :

if($event->getOrder()->getDeliveryModuleId() === FlatFeeDelivery::getModuleId())

**Comment by gillesbourgeat** [comment]
Hello and thanks,

Indeed, Would you do a pull request ?
